# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Knowledge"
  title = "Knowledge"
  identifier = "knowledge"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Agent"
  title = "Agent"
  parent = "knowledge"
  pageRef = "blog/agent"
  weight = 10

[[main]]
  name = "Go"
  title = "Go"
  parent = "knowledge"
  pageRef = "blog/go"
  weight = 20

[[main]]
  name = "Other"
  title = "Other"
  parent = "knowledge"
  pageRef = "blog/other"
  weight = 30

[[main]]
  name = "Work Notes"
  title = "Work Notes"
  parent = "knowledge"
  pageRef = "blog/work"
  weight = 40

[[main]]
  name = "Practice"
  title = "Practice"
  pageRef = "series"
  weight = 20

[[main]]
  name = "Tags"
  title = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "About"
  title = "About"
  pageRef = "about"
  weight = 40

[[main]]
  name = "More"
  title = "More"
  identifier = "more"
  pageRef = "more"
  weight = 50

[[main]]
  name = "Contributors"
  title = "Contributors"
  parent = "more"
  pageRef = "contributors"
  weight = 10

[[main]]
  name = "Website Analytics"
  title = "Website Analytics"
  parent = "more"
  url = "https://umami-blue-theta.vercel.app/share/BEzpGQVeCwg6CQqd"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/peakxy"
  weight = 400


# -- Footer Menu --
# The footer menu is intentionally empty.
