# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "知识"
  title = "知识"
  identifier = "knowledge"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Agent"
  title = "Agent"
  parent = "knowledge"
  pageRef = "blog/agent"
  weight = 20

[[main]]
  name = "Go"
  title = "Go"
  parent = "knowledge"
  pageRef = "blog/go"
  weight = 10

[[main]]
  name = "其他"
  title = "其他"
  parent = "knowledge"
  pageRef = "blog/other"
  weight = 40

[[main]]
  name = "工作沉淀"
  title = "工作沉淀"
  parent = "knowledge"
  pageRef = "blog/work"
  weight = 30

[[main]]
  name = "实战"
  title = "实战"
  pageRef = "series"
  weight = 20

[[main]]
  name = "标签"
  title = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "关于"
  title = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  name = "更多"
  title = "更多"
  identifier = "more"
  pageRef = "more"
  weight = 50

[[main]]
  name = "学习资料"
  title = "学习资料"
  parent = "more"
  pageRef = "more/learning"
  weight = 5

[[main]]
  name = "致谢"
  title = "致谢"
  parent = "more"
  pageRef = "contributors"
  weight = 10

[[main]]
  name = "网站统计"
  title = "网站统计"
  parent = "more"
  url = "https://umami-blue-theta.vercel.app/share/BEzpGQVeCwg6CQqd"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/peakxy"
  weight = 400


# -- Footer Menu --
# The footer menu is intentionally empty.
